// src/Global/routesList.js
export default [
  { path: "/" },
  { path: "/schedule" },
  { path: "/schedule/:season" },
  { path: "/roster" },
  { path: "/roster/:season" },
  { path: "/payments" },
  { path: "/store" },
  { path: "/donate" },
  { path: "/gallery" },
  { path: "/sponsorships" },
  { path: "/recruitment" },
  { path: "/recruitment/submissions" },
  { path: "/settings" },
  { path: "/checkout" },
  { path: "/checkout-success" },
  { path: "/pending-approval" },
  { path: "/admin" },
  { path: "/fundraiser" },

  { path: "/women" },
  { path: "/women/" },
  { path: "/women/schedule" },
  { path: "/women/schedule/:season" },
  { path: "/women/roster" },
  { path: "/women/roster/:season" },
  { path: "/women/payments" },
  { path: "/women/store" },
  { path: "/women/donate" },
  { path: "/women/gallery" },
  { path: "/women/sponsorships" },
  { path: "/women/recruitment" },
  { path: "/women/recruitment/submissions" },
  { path: "/women/settings" },
  { path: "/women/checkout" },
  { path: "/women/checkout-success" },
  { path: "/women/admin" },
  { path: "/women/fundraiser" },
];
